name: build segment cache

on:
  push:
    branches:
      - master
#  schedule:
## https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule
##            ┌───────────── minute (0 - 59)
##            │ ┌───────────── hour (0 - 23)
##            │ │ ┌───────────── day of the month (1 - 31)
##            │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
##            │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
##            │ │ │ │ │
##            │ │ │ │ │
##            │ │ │ │ │
##            * * * * *
#    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@master
      - name: Set up Node.js + pnpm
        uses: pnpm/setup@v1
        with:
          version: next-12
          runtime: node@26
          cache: true
      - name: setup git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: install deps
        env:
          PNPM_APPROVE_BUILDS: true
        run: |
          pnpm install --frozen-lockfile
          pnpm run ci:install
      - name: run script
        if: success()
        run: pnpm run ci:build
      - name: Push changes
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: packages/novel-segment/test/temp
          branch: cache
          force: true
